services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: router-bot-rabbitmq
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672

  krakend:
    image: devopsfaith/krakend:watch
    container_name: router-bot-krakend
    restart: unless-stopped
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    ports:
      - 8080:8080
    volumes:
      - ./services/registry/krakend:/etc/krakend

  redis:
    image: redis:7.4.2
    container_name: router-bot-redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    command: redis-server --save 60 1 --loglevel warning
