export enum EInjectionTokens {
  CORE_REDIS_OPTIONS = "CORE_REDIS_OPTIONS",
  MICROSERVICES = "MICROSERVICES",
  REGISTRY_SERVICE = "REGISTRY_SERVICE",
  MICROSERVICES_OPTIONS = "MICROSERVICES_OPTIONS",
}
